# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cs125' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cs125

  target 'cs125Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
